#!/usr/bin/env python
"""Regenerate the theme-content seed migration from src/gotiate/domain/theme_data/*.json.

The JSON files are the source of truth (DATABASE.md) -- this script is
how that content gets into Postgres, so a new theme set or an edited one
never needs hand-written SQL. Run it and paste the output into a fresh
migration file (supabase migration new seed_theme_content_vN), don't edit
a migration that's already been applied to a shared project.

Usage: python scripts/generate_theme_seed.py
"""

from __future__ import annotations

import json
from pathlib import Path

THEME_DATA_DIR = Path(__file__).parent.parent / "src" / "gotiate" / "domain" / "theme_data"


def _sql_string(value: str | None) -> str:
    if value is None:
        return "null"
    return "'" + value.replace("'", "''") + "'"


def generate() -> str:
    lines = ["-- Generated by scripts/generate_theme_seed.py -- do not hand-edit.",
             "-- Source of truth: src/gotiate/domain/theme_data/*.json", ""]

    for path in sorted(THEME_DATA_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        theme_set_id = data["theme_set_id"]
        version = data["version"]
        name = data["name"]

        lines.append(f"-- {theme_set_id} v{version} ({len(data['entities'])} entities)")
        lines.append(
            f"insert into theme_sets (theme_set_id, version, name) values "
            f"({_sql_string(theme_set_id)}, {version}, {_sql_string(name)});"
        )
        lines.append("insert into theme_entities (theme_set_id, theme_set_version, theme_key, display_name, ticker_symbol, is_locked, logo_url) values")
        rows = []
        for entity in data["entities"]:
            rows.append(
                "  ({}, {}, {}, {}, {}, {}, {})".format(
                    _sql_string(theme_set_id),
                    version,
                    _sql_string(entity["theme_key"]),
                    _sql_string(entity["display_name"]),
                    _sql_string(entity["ticker_symbol"]),
                    "true" if entity.get("is_locked") else "false",
                    _sql_string(entity.get("logo_url")),
                )
            )
        lines.append(",\n".join(rows) + ";")
        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    print(generate())
